---
title: "DATA607_Project2_data2"
author: "LeTicia Cancel"
output: html_document
---

# Dataset #2
##### **Source:** [Open Intro](https://openintro.org/stat/data/pokemon.csv)
##### **Data Description:** Dataset of 4 different Pokemon and their stats. Data points include attack type, strength, health, weight, and other important Pokemon stats. 
**Note:** A csv file containing Pokemon data will download to your machine when you click on the Open Intro link

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

--------
#### Load all libraries
```{r warning=FALSE, results='hide', message=FALSE}
#install.packages("kableExtra") #install this package if it is not already installed
library(knitr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(RCurl)
library(kableExtra)
library(tidyverse)
```

#### Load csv file from Github
```{r}
df2 <- read.csv(text = getURL("https://raw.githubusercontent.com/ltcancel/Project2/master/pokemon.csv"), header = TRUE, sep = ",")
head(df2)
```

plots
```{r}
ggplot(df2, aes(x = species, y = cp)) + geom_jitter()
```


```{r}

```

